using Avalonia.Media;

namespace NMSE.Core;

/// <summary>
/// Defines named colour slots for the Light and Dark application themes.
/// Colour values only - no dependency on any UI toolkit beyond Avalonia.Media.Color.
/// </summary>
internal static class ThemeColors
{
	internal sealed record Palette(
		Color Background,
		Color ForegroundText,
		Color SecondaryText,
		Color InputBackground,
		Color InputForeground,
		Color GridBackground,
		Color GridCellBackground,
		Color GridCellForeground,
		Color GridHeaderBackground,
		Color GridHeaderForeground,
		Color GridLineColor,
		Color SelectionBackground,
		Color TabBackground,
		Color TabForeground,
		Color TabSelectedBackground,
		Color ButtonBackground,
		Color ButtonForeground,
		Color MenuBackground,
		Color MenuForeground,
		Color StatusBarBackground,
		Color StatusBarForeground,
		Color MenuHighlightBackground,
		Color MenuBorder,
		Color ToolStripBorder,
		Color WarningOrange,
		Color ErrorRed,
		Color SuccessGreen,
		Color InfoBlue,
		Color ItemNameBlue,
		Color InventoryGridBg,
		Color InventoryIconBg,
		Color InventorySlotSelected,
		Color InventorySlotDeactivated,
		Color GridCellDisabledBackground,
		Color GridCellDisabledForeground,
		Color SyntaxBackground,
		Color SyntaxDefaultText,
		Color SyntaxKey,
		Color SyntaxString,
		Color SyntaxNumber,
		Color SyntaxBoolNull,
		Color SyntaxBrace,
		Color SyntaxGutterBg,
		Color SyntaxGutterNumber,
		Color SyntaxSelection,
		Color SyntaxCurrentLine,
		Color SplitterColor,
		Color SearchHighlightBackground,
		Color SearchHighlightCurrentBackground
	);

	internal static readonly Palette Light = new(
		Background:            SystemColors.Control,
		ForegroundText:        SystemColors.ControlText,
		SecondaryText:         Colors.Gray,
		InputBackground:       SystemColors.Window,
		InputForeground:       SystemColors.WindowText,
		GridBackground:        SystemColors.Control,
		GridCellBackground:    SystemColors.Window,
		GridCellForeground:    SystemColors.ControlText,
		GridHeaderBackground:  SystemColors.Control,
		GridHeaderForeground:  SystemColors.ControlText,
		GridLineColor:         Color.FromRgb(200, 200, 200),
		SelectionBackground:   SystemColors.Highlight,
		TabBackground:         SystemColors.Control,
		TabForeground:         SystemColors.ControlText,
		TabSelectedBackground: Color.FromRgb(212, 242, 255),
		ButtonBackground:      SystemColors.Control,
		ButtonForeground:      SystemColors.ControlText,
		MenuBackground:        SystemColors.MenuBar,
		MenuForeground:        SystemColors.MenuText,
		StatusBarBackground:   SystemColors.Control,
		StatusBarForeground:   SystemColors.ControlText,
		MenuHighlightBackground: SystemColors.MenuHighlight,
		MenuBorder:            SystemColors.ActiveBorder,
		ToolStripBorder:       Color.FromRgb(160, 160, 160),
		WarningOrange:         Colors.DarkOrange,
		ErrorRed:              Colors.Red,
		SuccessGreen:          Colors.Green,
		InfoBlue:              Colors.DarkBlue,
		ItemNameBlue:          Colors.DarkBlue,
		InventoryGridBg:       Color.FromRgb(30, 30, 30),
		InventoryIconBg:       Color.FromRgb(40, 40, 40),
		InventorySlotSelected: Color.FromRgb(70, 80, 100),
		InventorySlotDeactivated: Color.FromRgb(80, 20, 20),
		GridCellDisabledBackground: Color.FromRgb(240, 240, 240),
		GridCellDisabledForeground: Colors.LightGray,
		SyntaxBackground:      Colors.White,
		SyntaxDefaultText:     Color.FromRgb(30, 30, 30),
		SyntaxKey:             Color.FromRgb(0, 51, 179),
		SyntaxString:          Color.FromRgb(163, 21, 21),
		SyntaxNumber:          Color.FromRgb(9, 134, 88),
		SyntaxBoolNull:        Color.FromRgb(128, 0, 128),
		SyntaxBrace:           Color.FromRgb(60, 60, 60),
		SyntaxGutterBg:        Color.FromRgb(245, 245, 245),
		SyntaxGutterNumber:    Color.FromRgb(130, 130, 130),
		SyntaxSelection:       Color.FromRgb(173, 214, 255),
		SyntaxCurrentLine:     Color.FromRgb(255, 255, 228),
		SplitterColor:         Color.FromRgb(160, 160, 160),
		SearchHighlightBackground: Colors.LightYellow,
		SearchHighlightCurrentBackground: Colors.Yellow
	);

	internal static readonly Palette Dark = new(
		Background:            Color.FromRgb(37, 37, 38),
		ForegroundText:        Color.FromRgb(240, 240, 240),
		SecondaryText:         Color.FromRgb(140, 140, 140),
		InputBackground:       Color.FromRgb(30, 30, 30),
		InputForeground:       Color.FromRgb(220, 220, 220),
		GridBackground:        Color.FromRgb(37, 37, 38),
		GridCellBackground:    Color.FromRgb(45, 45, 48),
		GridCellForeground:    Color.FromRgb(220, 220, 220),
		GridHeaderBackground:  Color.FromRgb(62, 62, 66),
		GridHeaderForeground:  Color.FromRgb(220, 220, 220),
		GridLineColor:         Color.FromRgb(80, 80, 80),
		SelectionBackground:   Color.FromRgb(38, 79, 120),
		TabBackground:         Color.FromRgb(30, 30, 30),
		TabForeground:         Color.FromRgb(220, 220, 220),
		TabSelectedBackground: Color.FromRgb(50, 50, 52),
		ButtonBackground:      Color.FromRgb(62, 62, 66),
		ButtonForeground:      Color.FromRgb(220, 220, 220),
		MenuBackground:        Color.FromRgb(45, 45, 48),
		MenuForeground:        Color.FromRgb(220, 220, 220),
		StatusBarBackground:   Color.FromRgb(45, 45, 48),
		StatusBarForeground:   Color.FromRgb(180, 180, 180),
		MenuHighlightBackground: Color.FromRgb(80, 80, 90),
		MenuBorder:            Color.FromRgb(70, 70, 75),
		ToolStripBorder:       Color.FromRgb(70, 70, 75),
		WarningOrange:         Color.FromRgb(255, 180, 50),
		ErrorRed:              Color.FromRgb(255, 80, 80),
		SuccessGreen:          Color.FromRgb(80, 200, 80),
		InfoBlue:              Color.FromRgb(80, 160, 255),
		ItemNameBlue:          Color.FromRgb(80, 160, 255),
		InventoryGridBg:       Color.FromRgb(20, 20, 20),
		InventoryIconBg:       Color.FromRgb(30, 30, 30),
		InventorySlotSelected: Color.FromRgb(85, 95, 115),
		InventorySlotDeactivated: Color.FromRgb(100, 30, 30),
		GridCellDisabledBackground: Color.FromRgb(50, 50, 53),
		GridCellDisabledForeground: Color.FromRgb(100, 100, 100),
		SyntaxBackground:      Color.FromRgb(30, 30, 30),
		SyntaxDefaultText:     Color.FromRgb(220, 220, 220),
		SyntaxKey:             Color.FromRgb(86, 156, 214),
		SyntaxString:          Color.FromRgb(206, 145, 120),
		SyntaxNumber:          Color.FromRgb(181, 206, 168),
		SyntaxBoolNull:        Color.FromRgb(197, 134, 192),
		SyntaxBrace:           Color.FromRgb(180, 180, 180),
		SyntaxGutterBg:        Color.FromRgb(37, 37, 38),
		SyntaxGutterNumber:    Color.FromRgb(100, 100, 100),
		SyntaxSelection:       Color.FromRgb(38, 79, 120),
		SyntaxCurrentLine:     Color.FromRgb(50, 50, 55),
		SplitterColor:         Color.FromRgb(100, 100, 100),
		SearchHighlightBackground: Color.FromRgb(120, 100, 30),
		SearchHighlightCurrentBackground: Color.FromRgb(180, 150, 30)
	);

	internal static Palette Get(string theme) => theme switch
	{
		"Dark" => Dark,
		_ => Light
	};
}
